# https://docs.traefik.io/configuration/commons/

debug = true

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"

  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
        [[entryPoints.https.tls.certificates]]
          certFile = "/etc-traefik/traefik.crt"
          keyFile = "/etc-traefik/traefik.key"

[file]

[backends]
  [backends.auth]
    [backends.auth.servers.server1]
      url = "http://auth:8000"

[frontends]
  [frontends.default]
    backend="auth"
    passHostHeader = true
